x/register/client/cli/flags.go, x/register/client/cli/query.go, x/register/client/cli/tx.go, x/register/client/rest/tx.go, x/register/handler.go, x/register/keeper/indexing_node.go, x/register/keeper/keeper.go, x/register/keeper/resource_node.go, x/register/types/codec.go, x/register/types/events.go, x/register/types/msg.go
1, add resource/indexing node update tx
2, add zero value protection
=> Qb479 sds nodes update

x/sds/app_test.go, x/sds/client/cli/query.go, x/sds/client/rest/rest.go
- Resolved error in unit test of sds module
- Re-added prepay rest api, which was missing during code merge
=> Qb543 fix sds unittest

x/register/keeper/indexing_node.go, x/register/keeper/indexing_node_test.go, x/register/keeper/keeper.go, x/register/keeper/node_state_change.go, x/register/keeper/resource_node.go, x/register/register_test.go
Remove event splitting related changes
=> - replace nowTime by blockHeaderTime

x/register/handler.go
=> - fix a typo issue

app/app.go, x/pot/alias.go, x/pot/app_test.go, x/pot/client/rest/tx.go, x/pot/genesis.go, x/pot/handler.go, x/pot/keeper/distribute.go, x/pot/keeper/distribute_test.go, x/pot/keeper/keeper.go, x/pot/keeper/keeper_tests.go, x/pot/keeper/store.go, x/pot/pot_test.go, x/pot/types/codec.go, x/pot/types/distribute.go, x/pot/types/errors.go, x/pot/types/events.go, x/pot/types/genesis.go, x/pot/types/key.go, x/pot/types/msg.go, x/sds/app_test.go, x/sds/sds_test.go
1, Foundation account is changed to module account.
2, The ozone price supports decimals
3, Test cases update & fix
=> QB-629 POT module issues fix

x/register/keeper/keeper.go, x/register/keeper/node_state_change.go, x/register/types/events.go
split CompleteUnbondingNode event into CompleteUnbondingResouceNode and CompleteUnbondingIndexingNode
=> Qb 626 update unbonding event

x/register/keeper/keeper.go, x/register/keeper/querier.go
fixed unbonding and unboned staking
=> tiny fixes for register module

x/pot/types/codec.go, x/register/types/codec.go, x/sds/types/codec.go
- qb 709: rename Msg with Tx for concrete msgs
=> refactor/qb 709: rename Msg with Tx for concrete msgs

x/pot/handler.go, x/register/handler.go, x/register/types/events.go, x/sds/handler.go
- qb 707: add sender attrib to emit events after tx execution
=> fix: qb 707: add sender attrib to emit events after Tx execution

x/sds/client/rest/query.go, x/sds/keeper/keeper.go
change uozPrice type from Int to Decimal
=> fix/qb-756 fix uozPrice to Decimal

x/pot/client/rest/query.go, x/pot/client/rest/tx.go, x/pot/keeper/distribute.go, x/pot/keeper/querier.go, x/pot/keeper/utils.go, x/pot/types/params.go, x/sds/keeper/keeper.go, x/sds/types/msg.go
1. fixed the occurrence of height=0 when query reward.
2. fixed/added reward denom for reward distribution
3. added reward denom for prepay
4. fixed minor bugs
=> fix/qb730_fix_the _height_of_rest/cli_response

x/sds/handler.go
qb865: remove hex decoding from fileHash
=> fix/qb865: remove hex decoding from fileHash

x/pot/client/cli/tx.go, x/pot/client/rest/tx.go, x/pot/handler.go, x/pot/types/errors.go, x/pot/types/msg.go, x/pot/types/types.go
https://qsn.atlassian.net/browse/QB-779
Merge at the same time as this [sp PR](https://github.com/stratosnet/sp/pull/57) and this [sds PR](https://github.com/stratosnet/sds/pull/71)
- Add BLS signature fields in volume report transaction
=> feat/QB-779 volume report with BLS signature

cmd/stchaincli/faucet.go
- qb983: add support of multiple funding accs in Faucet
=> feat/qb983: add support of multiple funding accs in Faucet

README.md
1. removed details for code building
2. added recommended hardware/software 
3. updated all links for Tropos Incentive Testnet
=> doc/update readme.md for Tropos Incentive Testnet

x/pot/keeper/withdraw.go
=> fix/qb1010: fix panic withdraw

cmd/stchaincli/faucet.go
- fix faucet shutdown issue by multiplying quit channels
=> fix/qb983: fix faucet shutdown issue

x/register/genesis.go
- qb1040: fix price jump upon upgrade
=> fix/qb1040: fix price jump upon upgrade

x/register/handler.go, x/register/types/events.go
- qb-1026: add node tier related logic for pp activation
- qb-1026: add node tier related logic for update pp stake
- qb-1026: add stake_to_remove in unbonding_resource_node event
=> feat/qb1026: node tier related changes on broadcast events

cmd/stchaind/gen_idx_nodes.go, x/pot/app_test.go, x/pot/keeper/distribute.go, x/pot/keeper/slashing.go, x/pot/pot_test.go, x/register/alias.go, x/register/app_test.go, x/register/genesis.go, x/register/keeper/indexing_node.go, x/register/keeper/resource_node.go, x/register/register_test.go, x/register/types/genesis.go, x/register/types/keys.go, x/sds/app_test.go
1, remove unnecessary store of register module
2, genesis export issue fix
3, test case fix
=> Fix/register & pot module issue fix

app/app.go, go.mod, go.sum, types/address.go, types/address_test.go, types/codec.go, x/register/handler.go, x/register/keeper/node_state_change.go, x/register/types/events.go, x/register/types/indexing_node.go, x/register/types/msg.go, x/register/types/resource_node.go
- Add SdsAddress type to codec
- Fix indexing/resource node network address validation
- Add missing yaml dependency
- Update golang.org/x/sys version to support MacOS with golang 1.17 
- Fix network address type in event attributes
=> fix/ add SdsAddress to codec

x/pot/keeper/querier.go
Added filters to keep empty output from  pot/rewards/epoch/epoch API
=> fix/qb-1094 filter out empty outputs from pot/rewards/epoch/epoch API

types/account.go, x/evm/keeper/statedb.go
=> Fix/QB1237: fix account type issue

x/evm/keeper/statedb.go
Fix smart contract migration failed issue.
=> Fix/QB-1237:fix account type issue

x/register/genesis.go, x/register/keeper/meta_node.go, x/register/keeper/resource_node.go
- qb-1258: fix ModuleAcc init/mint in register/initGenesis
=> fix/qb1258: fix ModuleAcc init/mint in register/initGenesis

x/pot/client/cli/query.go, x/pot/client/rest/query.go, x/pot/keeper/querier.go, x/register/client/cli/query.go, x/register/client/rest/query.go, x/register/keeper/keeper.go, x/register/keeper/querier.go, x/sds/client/cli/query.go, x/sds/client/common/common.go, x/sds/client/rest/query.go, x/sds/keeper/querier.go
1. added query params of register/pot/sds modules by command line, restful request and grpc request 
2. added query total number of bonded resource/meta nodes in register module  by command line, restful request and grpc
=> feat/qb-1164 added query register/sds/pot module params by grpc, cmd and restful

third_party/proto/cosmos/staking/v1beta1/staking.proto, x/pot/client/cli/query.go, x/pot/client/rest/query.go, x/pot/client/rest/rest.go, x/pot/keeper/querier.go, x/pot/types/querier.go, x/register/client/cli/query.go, x/register/client/rest/query.go, x/register/keeper/keeper.go, x/register/keeper/querier.go, x/sds/client/cli/query.go, x/sds/client/common/common.go, x/sds/client/rest/query.go, x/sds/keeper/querier.go
1. change /pot/rewards/epoch/{epoch}?wallet={address} → /pot/rewards/wallet/{walletAddress}?epoch={epoch}
2. removed unnecessary params in /pot/rewards/epoch
3. modified doc
=> fix/qb-1255: PoT query for volume report path adjust

x/register/genesis.go, x/register/keeper/keeper.go, x/register/keeper/meta_node.go, x/register/keeper/resource_node.go, x/register/types/errors.go
- qb1265: Change Mint to SendCoins in register/initGenesis() to avoid jump of total supply
=> fix/qb1265: Change Mint to SendCoins in register/initGenesis() to avoid jump of total supply

rpc/apis.go, server/json_rpc.go, server/start.go
Start JsonRPC service with eth chain id from genesis file instead of getting from the store.
=> Fix/Qb-1275: Seed node start error

README.md
=> doc/update README.md

app/test_helpers.go, x/pot/app_test.go, x/sds/oz_price_test.go
- qb1039: add uoz price unittest
=> feat/qb1039: add uoz price unittest

x/evm/keeper/msg_server.go, x/pot/keeper/msg_server.go, x/pot/types/errors.go, x/pot/types/params.go, x/register/keeper/msg_server.go, x/register/types/errors.go, x/register/types/msg.go, x/sds/keeper/msg_server.go, x/sds/types/errors.go, x/sds/types/msg.go, x/sds/types/params.go
- qb-1257: wrap all errors in handler and ValidateBasic()
=> fix/qb1257: wrap all errors in handler and ValidateBasic()

x/register/keeper/msg_server.go
=> Feat/QB-1460: Token denom update

x/register/keeper/keeper.go
- qb1542: fix truncate impl of noz supply
=> fix/qb1542: fix truncate impl of noz supply

client/utils.go, x/pot/client/rest/query.go, x/pot/keeper/querier.go, x/pot/types/querier.go
=> Fix/QB-1577: The query pagination currently not save query time

Makefile, tests/e2e/Dockerfile, tests/e2e/entrypoint.sh
Add `Dockerfile` and `entrypoint.sh` for integration tests.
=> QB-1532 Add Dockerfile for integration test

x/pot/keeper/keeper.go, x/pot/keeper/msg_server.go, x/pot/types/errors.go, x/pot/types/expected_keepers.go, x/pot/types/msg.go, x/register/keeper/meta_node.go, x/register/keeper/msg_server.go, x/register/types/errors.go
Add report owner validation  for MsgVolumeReport/MsgSlashingResourceNode/MsgUpdateEffectiveStake
=> Fix/QB-1716: Add report owner validation 

x/register/keeper/keeper.go, x/register/keeper/meta_node.go, x/register/keeper/resource_node.go
Please merge [https://github.com/stratosnet/stratos-chain/pull/276](https://github.com/stratosnet/stratos-chain/pull/276) first.
=> Fix/Qb-1873: Concurrent map writes crash in register keeper

x/pot/keeper/keeper.go, x/pot/keeper/migrations.go, x/pot/module.go, x/pot/types/params.go, x/register/keeper/migrations.go, x/register/module.go, x/sds/keeper/migrations.go, x/sds/module.go
1, Default reward denom related param value update & typo fix
2, Migrate error code remove & set the consensus version to 1
=> Feat/QB-1883: Mainnet preparation

Dockerfile, tests/e2e/Dockerfile, x/pot/keeper/grpc_query.go, x/pot/keeper/store.go
When query epoch 0, return the latest epoch
=> Feat/QB-2269: Update VolumeReport query API

rpc/backend/evm_backend.go, rpc/backend/utils.go, rpc/namespaces/ethereum/debug/api.go, rpc/namespaces/ethereum/eth/api.go, rpc/namespaces/ethereum/eth/filters/api.go, rpc/types/utils.go, x/evm/context.go, x/evm/keeper/eip1559.go, x/evm/types/chain_config.go
will throw right now `the data is available only in the archive node` if data related to cosmos sdk and when it was pruned
=> Update web3 logic to show archive node state + small fix for block
