- Makefile
- x/register/handler.go
- x/register/types/events.go
https://qsn.atlassian.net/browse/QB-446
Associated PR: [SDS#21](https://github.com/stratosnet/sds/pull/21)
The CreateResourceNode message will now publish the pubkey in the event instead of only the address.
> QB-446 CreateResourceNode Returns Pubkey

- helpers/antehelper.go
- x/register/allow_ed25519_gas_test.go
- x/register/register_test.go
- x/register/types/errors.go
- x/register/types/msg.go
1. in ./x/register/types/errors.go, added  `ErrED25519InvalidPubKey`
2. in ./helpers/antehelper.go, change to` return registertypes.ErrED25519InvalidPubKey`
3. in ./x/register/msg.go, removed `Nodesign ` in `MsgCreateResourceNode `. Removed the two signers (keep only owner) in `GetSigners` for both resource node and indexing node. 
4. Unit test passed using secp256k1 pubkey and got an error "ED25519 public keys are unsupported" if using ED25519 pubkey.
> modified the double-signing to single signing, test passed using secp256k1 pubkey

- cmd/stchaind/loadtest.go
- x/sds/client/common/common.go
- x/sds/client/rest/query.go
- x/sds/client/rest/rest.go
- x/sds/keeper/keeper.go
- x/sds/keeper/querier.go
- x/sds/module.go
- x/sds/types/querier.go
- Add rest api for sds/simulatePrepay/{amt}
- Add rest api for sds/uozPrice
- Add rest api for sds/uozSupply
- Modified loadtest.go to get adapted to increased gas consumption
Notes:
- Total uoz supply now returns a fake total, leaving TODO for later implementation since a series of changes ahead to be done
- Apis are created in sds module, since sds contains all needed dependencies (pot and register module)
> Qb 548 add ozone related apis

- x/register/types/msg.go
https://qsn.atlassian.net/browse/QB-533
Removing the second signer for the IndexingNodeRegistrationVote message because the `VoterNetworkAddress` is an ed25519 key, which isn't supported by cosmos-sdk.
> QB-533 Indexing Node Vote Single Signer

- vue/package-lock.json
According to the dependabot alert, updated versions. For "ansi-html", it is required >= 0.0.7, but this is the last version, no updated version is available. Now I changed it to 0.0.8. If it does not work, we have to remove it from the requirements.
> updated vue dependency according to denpendabot alert

- x/sds/client/cli/tx.go
- x/sds/client/rest/rest.go
- x/sds/handler.go
- x/sds/keeper/keeper.go
- x/sds/types/msg.go
1. in MsgFileUpload, change the type of FileHash field from []byte to string
2. accordingly, change types of FileHash field in client/cli/tx, client/rest/rest and types/handler   in SDS module
> Fix/Qb-801 change type of FileHash from []byte to string

- x/pot/app_test.go
- x/pot/keeper/distribute.go
- x/pot/keeper/distribute_test.go
- x/pot/keeper/incentive_testnet_distribute.go
- x/pot/keeper/store.go
- x/pot/types/key.go
- x/register/genesis.go
- x/register/keeper/keeper.go
- x/register/types/errors.go
- x/register/types/genesis.go
- x/register/types/keys.go
- x/register/types/params.go
- x/sds/app_test.go
- x/sds/genesis.go
- x/sds/keeper/keeper.go
- x/sds/keeper/querier.go
- x/sds/types/errors.go
- x/sds/types/genesis.go
- qb1029: move TotalUnissuedPrepay from pot to register
- qb1029: export currUozPrice instead of initalUozPrice into new genesis of register
- qb1029: TotalUnissuedPrepay added to genesis
- qb1029: uozSupply api can now correctly return total supply
> fix/qb1029: fix export function for register/pot/sds module

- go.mod
- go.sum
- x/pot/app_test.go
- x/pot/client/rest/query.go
- x/pot/genesis.go
- x/pot/keeper/distribute.go
- x/pot/keeper/distribute_test.go
- x/pot/keeper/keeper.go
- x/pot/keeper/querier.go
- x/pot/keeper/slashing.go
- x/pot/keeper/store.go
- x/pot/pot_test.go
- x/pot/types/genesis.go
- x/pot/types/key.go
- x/pot/types/msg.go
- x/register/alias.go
- x/register/app_test.go
- x/register/genesis.go
- x/register/keeper/indexing_node.go
- x/register/keeper/resource_node.go
- x/register/keeper/slashing.go
- x/register/types/errors.go
- x/register/types/genesis.go
- x/register/types/keys.go
- x/sds/app_test.go
1, Move slashing store from pot module to register module.
2, Move slashing genesis info from pot module to register module.
3, Slashing store key is changed from p2p address to wallet address.
4, Deduct slashing amount when:
a, calculate upcoming mature reward, deduct from mature_total & upcoming mature reward.
b, unstaking indexing node.
c, unstaking resource node.
5, Switch reward distribution logic to mainnet.
6, Reward mature issue fixed.
7, Remove reward address pool.
8, Update store keys.
9, Unit test issue fix.
> Feat/QB-1061: finish the slashing deduction logic

- app/app.go
- app/utils.go
- client/keys.go
- client/keys/add.go
- cmd/stchaind/genaccounts.go
- cmd/stchaind/genmetanodes.go
1, Now is able to use the --algo flag to create accounts for specific key types, the default value is cosmos secp256k1.
2, For normal query with cosmos, returns cosmos base account.
3, Only return eth account for evm related rpc.
4, Use cosmos base account in the genesis file.
5, rename genidxnodes to genmetanodes
> Feat/QB-1241 Make the BaseAcccount compatible with EthAccount 

- x/pot/client/rest/query.go
Allow empty walletAddress parameter for /pot/rewards/{epoch} query.
> Fix/QB-1253: Pot query issue fix

- x/pot/keeper/distribute.go
Don't deduct matured rewards any more.
> Feat/Qb-1357: Deduct future maturing rewards for slashed amount

- cmd/stchaind/root.go
- server/config/config.go
- server/start.go
Add default value & minimal value restriction of minimum-gas-prices on app.toml
Default value: 1gwei
Minimal value: 0.01gwei
If value is set less than the minimal value, then use default value instead.
> Feat/QB1494: Add default & minimal value for minimum-gas-prices

- cmd/stchaind/root.go
https://qsn.atlassian.net/browse/QB-1344
- Make the BaseApp actually use the IAVL cache size from the config (instead of always using the IAVL default of 500000)
- To reduce memory usage, change the `iavl-cache-size` in `app.toml` to a more reasonable value. The default config value is 781250, which keeps way too many nodes in memory. Maybe 10000 would be more appropriate
> fix/QB-1344 Read IAVL cache size from config

- x/pot/abci.go
- qb1586: fix improper error handling in pot/endBlocker to print detailed error msg
> fix/qb1586: fix improper error handling in pot/endBlocker to print detailed error msg

- .github/workflows/pull-request
- Makefile
- x/pot/app_test.go
- x/register/types/resource_node.go
- x/sds/oz_price_test.go
https://qsn.atlassian.net/browse/QB-1603
- Fix unit tests
- Add coverage cmd to makefile to calculate test coverage (current coverage: 9.1%)
> test/QB-1603 Fix unit tests

- cmd/stchaind/main.go
- go.mod
Go1.19 rewrite the sort functions.
The order of sorted results will be different between go1.18 & go1.19 if the values of the compared elements are equal.
Import new type introduced by go1.19, forcing to build with go1.19.
> Fix/Qb-1632: App hash different between build with go1.18 & go1.19

- x/evm/genesis.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/statedb.go
- x/evm/statedb/interfaces.go
- x/evm/statedb/state_object.go
- x/evm/statedb/statedb.go
Passed test:
https://github.com/stratosnet/stratos-evm-tests/blob/master/test/Destroy.test.js
> QB-1761: Fix evm contract destroy

- x/sds/keeper/msg_server.go
Remove unnecessary validation.
Following Prepay() method only accept token with denom defined in the module params.
> Fix/Qb-1751: Inconsistent token denoms

- x/pot/keeper/distribute.go
- x/register/keeper/keeper.go
- x/register/keeper/resource_node.go
- x/register/keeper/store.go
- x/register/types/msg.go
- x/sds/keeper/keeper.go
- qb1747: fix validation of msg update effective stake
- qb1746: fix extreme case which will make remainingOzoneLimit fall to a negative value
- qb1762: fix unnecessary format convertion of sdk.int
> fix/qb1747: fix validation of msg update effective stake

- x/pot/keeper/distribute.go
- x/register/keeper/keeper.go
- x/register/keeper/resource_node.go
- x/register/keeper/store.go
- x/register/types/msg.go
- x/sds/keeper/keeper.go
- qb1747: fix validation of msg update effective stake
- qb1746: fix extreme case which will make remainingOzoneLimit fall to a negative value
- qb1762: fix unnecessary format convertion of sdk.int
- qb1752: fix deletion in iteration while DequeueAllMatureUBDQueue
> fix/qb1752: fix deletion in iteration while DequeueAllMatureUBDQueue

- Dockerfile
- Makefile
- entrypoint.sh
* Use `entrypoint.sh` to update permissions when we mount the folder to the container.
* Update Dockerfile to use higher Golang version and new dependencies.
* Update Makefile to easily build docker images.
```
docker build -t stchain .
docker run -d --name stchain-node stchain
```
It will connect the default chain on [stratos-chain-testnet](https://github.com/stratosnet/stratos-chain-testnet).
If you want to keeps all configuration and data files outside the container, you can follow the script:
```
STCHAIND_HOME=~/stchaind-home
MONIKER=test-node
CONTAINER_NAME=stchain-node
GENESIS_FILE_URL=https://raw.githubusercontent.com/stratosnet/stratos-chain-testnet/main/genesis.json
CONFIG_FILE_URL=https://raw.githubusercontent.com/stratosnet/stratos-chain-testnet/main/config.toml
make …
```
> QB-1793 Update Dockerfile

- app/ante/eth.go
- app/ante/handler_options.go
- app/ante/interfaces.go
- app/app.go
- rpc/types/utils.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/keeper.go
- x/evm/keeper/state_transition.go
- x/evm/types/msg.go
- x/evm/types/msg_cosmos.go
- x/evm/types/utils.go
Tests (https://github.com/stratosnet/stratos-evm-tests/blob/feat/ST-110/add-ethereum-data-to-cosmos-msg-processing/test/CosmosData.test.js):
[x] Delegate/undelegate
[x] Send/MultiSend
[x] Prepay
[x] Create validator
[x] EVM Mas 
Gas usage delegate: ~72313 Gas (if nobody delegated) ~107871 (if already something delegated)
Gas usage undelegate: ~123335 - 155190 (varies)
(Done) ~~Still not finalized `eth_call` and `eth_estimateGas`. `eth_call` must be implemented in order to check tx before as if tx is failed, it is not marked as failed like normal evm tx.~~
> [Merge step 2] PoC: Any cosmos/stratos msg through MsgEthereumTx

- app/app.go
- app/app_config.go
Set DefaultPowerReduction to 1e13, which supports 8 digit stos delegation value.
Since total_supply is 100M stos, which is 9 digit integer, this powerReduction is safe enough to prevent overflow.
> Fix/ Set default power reduction on start
